# server
server:
  runMode: debug # debug / test / release
  host: localhost
  port: 8999
  timezone: Asia/Shanghai

# db
mysql:
  store_platform:
    host: localhost
    port: 3306
    database: test
    user: root
    password: root
    timezone: Asia/Shanghai

# cache
redis:
  store_platform:
    host: localhost
    port: 6379
    database: 0
    password:

logrus:
  filename: ./app.log

logs:
  app:
    level: debug
    file: ./runtime/log/app.log